### PR TITLE
NONE, TAG_CONS, TAG_SOME, MAX_FIXNUM and MIN_FIXNUM constants

### PR DESCRIPTION
**Pull request by tizoc**

### CODE REVIEW

**Comment by zshipko** [comment]
Looks good, I will merge once the tests pass and can do another release for these changes if you need them on crates.io, but if you have more changes coming I will hold off on the release.

**Comment by tizoc** [comment]
@zshipko what I submitted here is what I use in ocaml-interop that would be better defined in ocaml-sys. For now I don't have plans of submitting other changes, but I guess you can wait until tomorrow, just in case.

Something that I switched from ocaml-interop to ocaml-sys version is `val_int` and `int_val`. The difference is that the now-removed versions from ocaml-interop where marked as unsafe ([see here](https://github.com/simplestaking/ocaml-interop/pull/12/commits/8cb1f1400c4313bd3efd231b8f1af1f70dd4f14a#diff-44fea3239f0e30a41cfdbf062f98b88dL47-L58)). The reasoning behind that was that the user must be aware of the possibly lost bit when making the conversion + maybe be careful about converting pointers into OCaml fixnums (this one is probably not a big deal, I just had it as an unsafe with an assert as a safeguard, helps with debugging).

In ocaml-interop those are not exposed, but only used internally, so it makes no difference. But since ocaml-sys exposes those two functions, this may be something worth considering.

The higher level version of `Rust Int -> OCaml Fixnum` conversion (this one is exposed) in ocaml-interop is implemented as two methods instead: one `_unchecked` version, marked as `unsafe`, and then the regular version that [returns a `Result` instead](https://github.com/simplestaking/ocaml-interop/blob/master/src/value.rs#L170-L181). Not the final version (I'm considering just using `Option` instead), but the overall idea is to make that possible failure explicit.

**Comment by zshipko** [comment]
Very cool - I appreciate the work you're doing to ensure safety. ocaml-rs definitely has some issues on that front - I could imagine an `ocaml-rs` rewrite on top of `ocaml-interop` that most provides the derive macros and things like that.

I will make a note to mark those as unsafe - to be honest, I never really expected anyone to use `ocaml-sys` so I imagine there are some other things worth cleaning up in there!

**Comment by tizoc** [comment]
@zshipko as I keep iterating on it, I think `ocaml-interop`'s API will become closer to `ocaml-rs` (in particular, if I can pull it off I think the way functions are declared so that they can be called from OCaml, and the way complex values are declared so that they can converted from/to OCaml is going to become much closer to `ocaml-rs` for example). There are also some features currently missing in `ocaml-interop`, like for example support for Custom blocks, that I think will end looking very much the same as in `ocaml-rs`.

So more than thinking about implementing one on the top of the other, what I think would be cool if possible, would be for both libraries to eventually converge (both work at the same level of abstraction after all, with `ocaml-sys` working at a lower level).

The biggest difference between two libraries is in how each approaches typing and lifetimes -- with `ocaml-rs` favoring a more dynamic approach (`Value` can be interpreted in different ways, and lifetimes are not used to enforce OCaml's GC rules), and with `ocaml-interop` being stricter in terms of typing and lifetimes from the ground up (sacrificing API convenience along the way, but with each iteration the API gets better and closer to `ocaml-rs`'s).

**Comment by zshipko** [comment]
Cool, makes sense - I think finding the middle-ground between the two would make a very nice interface! I have spent a very small amount of time working on making the GC explicit with matching lifetimes (as in `ocaml-interop`) and I think that path is ideal. I've hit some issues where `ocaml-rs` is doing too many allocations causing OOM errors, so fixing that is a priority for me. Combining the two libraries is definitely something I would be interested in working together on once you've reached the point with `ocaml-interop` where you feel like that makes sense!

**Comment by tizoc** [comment]
> I could imagine an ocaml-rs rewrite on top of ocaml-interop that most provides the derive macros and things like that.

Lol, thinking more about this, I think we have the same idea in mind. What I wanted to clarify is that the new API would not be 100% backwards compatible (what would change is for `Value` to become something like `Value<T>`, + lifetimes). All the `derive` stuff is what I would like to have working in `ocaml-interop`.

**Comment by zshipko** [comment]
Yep, I am open to changing the API to allow for more safety - that's why I haven't released a 1.0 for ocaml-rs yet.

**Comment by tizoc** [comment]
>  I've hit some issues where ocaml-rs is doing too many allocations causing OOM errors, so fixing that is a priority for me. 

Regarding this, I have some ideas but I have not reached the point where I can try those yet. Maybe your issue is not related to what I'm talking about here, but I think it is something that would be useful to have anyway.

Something I have been pondering about, is about how to better handle the management of deep complex data structures (records, with fields that are also records, which may then contain arrays, etc etc) that have to be interacted with from the Rust side.

The usual thing to do here is to perform a conversion from the OCaml value into a Rust value. But in these cases performing a direct conversion into an equivalent Rust structure is (in most situations) unnecessarily costly, and an easy place to have not-so-obvious performance issues.

So what I had in mind is for a `derive` annotation for structs/enums that can implement `impl OCaml<T>` for those `T`, defining operations (field accessors for structs is an obvious example) that work directly on the value without converting it into a Rust value. This would work in a similar way to how you already implement direct operations into OCaml values as `Value` methods. In `ocaml-interop` this is similar but operations are only implemented for the `OCaml<T>` where it makes sense (`OCaml<OCamlInt>` for example does not contain a method that indexes an array or obtains the tail of a list for example).

It is not as simple of course because Rust will not let code from another crate define an `impl OCaml<T>` for a new `T` without defining a new wrapper type, but I guess this can be worked around when the time comes.

**Comment by zshipko** [comment]
That is a great idea - I think using the OCaml memory representation without converting back and forth between Rust would be extremely beneficial. There is still the case where you do want to convert an OCaml array into a Vec, but it's probably much less common than accessing a few elements of the array - I will need to spend some thing thinking about what that interface could look like.

**Comment by tizoc** [comment]
Yes, you would still have the regular conversion in this case (like it exists in ocaml-rs and ocaml-interop in their current forms). The idea here would be an extended version of ocaml-rs's derivers (ocaml-interop uses macros for this, but only because of specific needs in TezEdge, may not be needed in the future) to, in addition of implementing `To`/`From` like it does now, to also be able to derive a `View` (or something like that) from the same declaration.

Every individual value will then have a `From` implementation as always, so when working with complex structures you would then be able to only convert what you need explicitly.

**Comment by zshipko** [comment]
I see, that does sound nice! The derive code could definitely use some attention before trying to modify or extend it so I will see if there's anything I can clean up there - it may also make sense to start from scratch and just copy some parts of the current `ocaml-derive`.

**Comment by tizoc** [comment]
Hi @zshipko, I noticed that you made a new release (0.18) a few days ago, what changed? (las commit on master is from 10 days ago, adding the new constants from this PR, but 0.18 doesn't seem to include them).

**Comment by zshipko** [comment]
Ah that is a mistake, I think I switched workstations and forgot to pull before making the release. I will release 0.18.1 with those changes. Sorry about that

**Comment by tizoc** [comment]
No worries, and thank you!

**Pull request merged**
