### PR TITLE
Call overhead benchmark

### PR DESCRIPTION
**Pull request by crackcomm**
It now shows overhead during `dune runtest`.

### CODE REVIEW

**Comment by crackcomm** [comment]
It's a shame the interface of core_bench is different in 4.06. The default quota is 10s per function.

**Comment by zshipko** [comment]
Thanks, this looks good! `core_bench` seems like a pretty heavy library (lots of dependencies) and since it is causing issues on 4.06, maybe there is an alternative? I will look into it and see if there's anything similar out there.

**Comment by tizoc** [comment]
@zshipko instead of running it for every OS, I would make it a separate pipeline. By doing that there is no need to be compatible with any particular version, just test on Linux on a recent OCaml.

A more lightweight alternative is https://github.com/mirage/bechamel

**Comment by zshipko** [comment]
#61 has been merged. Thanks!

**Pull request closed without merging**
