### PR TITLE
Fix runtime handle recovery in macros.

### LINKED ISSUE #57: Call overhead
Hey, I had my code locked to revision [8bfcd27](https://github.com/zshipko/ocaml-rs/commit/8bfcd27b0abce77a8612fc77f4f30526bb1c8970) and since I updated the overhead of a call went from `11ns` up to `196ns`. I guess some of the speed was sacrificed for security but this seems huge, is there anything I can do about it? I want to find the reason and fix it if possible but a lot of changes were made so you might be able to guide me where to look for the cause.

### PR DESCRIPTION
**Pull request by tizoc**
Fixes #57

### CODE REVIEW

**Comment by tizoc** [comment]
@zshipko test pass, and seems to have fixed the issue, but I may have missed something (not entirely sure how ocaml-rs initializes the runtime when the caller is a Rust program). In the case where it is an OCaml calling Rust then there is no issue here, because if the calling program is in OCaml, the runtime has been initialized already.

**Comment by zshipko** [comment]
Great! Right now there is a function for the user to initialize the runtime: https://github.com/zshipko/ocaml-rs/blob/master/src/runtime.rs#L37 - but this is a holdover from the old implementation - I should update it to just call `ocaml_interop::Runtime::init`.

The interface for calling into OCaml from Rust wasn't initially very well thought out, so I hope to improve that a bit in the next iteration.

**Comment by tizoc** [comment]
@zshipko ok good, calling `OCamlRuntime::init` will automatically make it work for when you upgrade to the new version that uses `BoxRoot`, because right now boxroots require an initialization call which happens inside `OCamlRuntime::init` (that will not be true anymore in the future, but for now it is required).

**Comment by crackcomm** [comment]
Tests on my codebase are all good and in benchmarks it's much faster, thanks!

**Comment by zshipko** [comment]
Alright, `0.20.1` has been released: https://crates.io/crates/ocaml/0.20.1

**Pull request merged**
