### PR TITLE
Major overhaul, work toward 1.0 release

### PR DESCRIPTION
**Pull request by zshipko**
- Remove `Tag` enum
- Split out `core` module into `ocaml-sys` crate
    * `ocaml-sys` is now `no_std`
- Replace `caml!` with `ocaml::func`
- Pulled in and updated derive macros from rust-ocaml-derive
- Remove `Value::i32`, `Value::i64`, etc.. in favor of `Value::int`
- Removed non-exn `call` functions
- Set up CI
- Add `Custom` trait and `custom!` macro for creating custom types
- Remove raise functions in favor of result type
- Convert global root functions  to take mutable pointers

### CODE REVIEW

**Comment by bkontur** [comment]
Wow, I see, you did a great work here. Interoperability for Option, I was really missing in 0.9.X. And derive for structs and functions looks much nicer than macros before and it simplifies some stuff.

And it would be cool to have test here, which starts in rust (cargo test) and calls ocaml, thx.

**Comment by bkontur** [comment]
Do you have any bench/performance comparison between 0.9.X and this 0.10 version?

**Comment by zshipko** [comment]
Hey, glad this stuff looks good to you.

Improving the tests is definitely something I want to do after the API is cleaned up. Sometime in the next few weeks probably.

Writing benchmarks may or may not be a part of that, however If you have some code you're using for testing performance I'd be happy to include that.

**Comment by bkontur** [comment]
Do you have any idea, when you merge this? :)

**Comment by zshipko** [comment]
Hoping to wrap up this branch over the weekend, if possible. There will likely be some more updates after that, but hopefully the majority of the rewrite will be done.

**Comment by bkontur** [comment]
Hello, I see you finished it, great work :)
When will it be ready here https://crates.io/crates/ocaml?
Thank you :)

**Comment by zshipko** [comment]
I can publish a beta version some time this week but would like to get some better testing in place first since a lot of this is new.

**Comment by zshipko** [comment]
@bkontur Just updated crates.io: https://crates.io/crates/ocaml

Please test it out and let me know if you run into any issues. I hope to publish a 1.0 release in the next few months!

**Pull request merged**
